AWSTemplateFormatVersion: '2010-09-09'
Description: Creates an Amazon Route 53 hosted zone and acm cert

Parameters:
  
  EnvironmentName:
    Type: String
    Description: "Environment Name"
    AllowedValues:
      - development
      - sandbox
      - staging
      - production
    Default: staging
  DomainName:
    Type: String
    Description: The DNS name of an Amazon Route 53 hosted zone.
    AllowedPattern: (?!-)[a-zA-Z0-9-.]{1,63}(?<!-)
    ConstraintDescription: must be a valid DNS zone name.

Resources:
  
  RepotingSiteDNSZone:
    Type: AWS::Route53::HostedZone
    Properties:
      HostedZoneConfig:
        Comment: !Join ['', ['Hosted zone for ', !Ref 'DomainName']]
      Name: !Ref 'DomainName'
  
  SiteCert:
    Type: AWS::CertificateManager::Certificate
    Properties:
      DomainName: !Ref DomainName         
      DomainValidationOptions:
        - DomainName: !Ref DomainName
          ValidationDomain: !Ref DomainName       
      ValidationMethod: DNS


Outputs:
  
  ReportingSiteDNSZoneID:
    Value: !Ref RepotingSiteDNSZone
    Description: Repoting site DNS ZoneID
    Export:
      Name: !Sub '${EnvironmentName}-ReportingSiteDNSZoneID'
  
  SiteCertARN:
    Value: !Ref SiteCert
    Description: Site cert ARN
    Export:
      Name: !Sub '${EnvironmentName}-SiteCertARN'


      